### ISSUE TITLE
wrong classname - deprecated in PHP7

### ISSUE THREAD

**Issue by schnuti** [mathiasverraes/jdump#31]
I got an errormessage after installing Joomla 3.5.0 on a testystem XAMPP with PHP7.=>

"Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP ... "

It looks as replacing the methodname with __construct fix it and I guess it's B/C =>

```
class plgSystemDump extends JPlugin
{
 /*
   function plgSystemDump(& $subject, $params) {
      parent::__construct($subject, $params);
   }
*/

function __construct(& $subject, $params) {
   parent::__construct($subject, $params);
}
```

**Comment by cheesegrits** [comment]
I submitted a PR on this

https://github.com/mathiasverraes/jdump/pull/33
