### ISSUE TITLE
Count problem of jdump with php 7.2

### ISSUE THREAD

**Issue by saman222** [mathiasverraes/jdump#36]
Hi...
I use php 7.2 in my host and see this error in my joomla pages:
Warning: count(): Parameter must be an array or an object that implements Countable in /home2/******/domains/*******/public_html/plugins/system/dump/dump.php on line 43
it seems problem with this version of php (and also 7.1) and when i change my php version to 7.0 it is not show this error.

**Comment by gruz** [comment]
Can you please propose any solution? Thanks.

**Comment by gruz** [comment]
@Sophist-UK I should be able to merge as well.

**Comment by Sophist-UK** [comment]
Ok - fix is easy and on its way.

**Comment by mathiasverraes** [comment]
My first guess would be that $userstate is null when there are no nodes, so casting that to an empty array would fix that. I didn't look into it properly though, I'm on my phone rn.

**Comment by Sophist-UK** [comment]
@mathiasverraes Exactly that - but rather than cast it to array (which would have been equally good), I put an empty array as default to getState.

**Comment by mathiasverraes** [comment]
awesome, cheers :)
